### PR TITLE
Towards Python3 compatibility

### PR DESCRIPTION
**Pull request by michaelchughes**
python3_latest branch, with these fixes

* Passes all doctests in tests/
* Passes all nosetests in tests/

TODO:

* [x] Verify these pass in python 3+ (not just 2.7)
* [x] Verify endtoend tests
* [x] Verify the example gallery still works

### CODE REVIEW

**Comment by michaelchughes** [comment]
Latest commit I've confirmed that the endtoend tests for XData, SeqXData, and WordsData all work.

Also confirmed side-by-side passing of python2 and python3 installs. 

Just need to confirm the examples gallery works OK, and we can accept and merge this PR

**Comment by XiChen-97** [comment]
The example gallery works well, several errors have been fixed.

**Comment by vineetbansal** [comment]
Hello @XiChen-97 .. thanks for the effort to port `bnpy` to Python 3. We're porting our own genomic codebase (https://github.com/raphael-group/hatchet) which uses `bnpy` to Python 3 and are looking forward to this release.

Till your release is official, we plan to pull code from this `python3_latest` branch for the duration of the transition (for testing purposes only). One of things we have had problems with `bnpy` in the past is that because it needs `cython` as a build dependency but doesn't explicitly list it (both in the Python 2 version and now the Python 3 version), a `pip install` always fails unless `cython` is already installed in the current environment. This presents a problem when we list `bnpy` as a dependency in our `requirements.txt` or `environment.yml`, since all packages are built in their own isolated environments (and setuptools doesn't know that it needs to `cython` in the one that it will use to build `bnpy`).

We have thus have to add a `pyproject.toml` to the location where we git clone your repository (see https://www.python.org/dev/peps/pep-0517/) with the following content:
```
[build-system]
requires = ["setuptools>=40.8.0", "wheel", "cython"]
```

This seems to work great. You may want to add a corresponding file to your package folder as well, so we can remove the hack on our end.

**Comment by michaelchughes** [comment]
Thanks for the heads up and great info about the build requirements. We are hoping to get this integrated soon. Sorry I am slow! Trying to get my semester off the ground first.

Best,
Mike

On Sep 4, 2020, at 10:10 AM, Vineet Bansal <notifications@github.com> wrote:


Hello @XiChen-97 <https://github.com/XiChen-97> .. thanks for the effort to port bnpy to Python 3. We're porting our own genomic codebase (https://github.com/raphael-group/hatchet <https://github.com/raphael-group/hatchet>) which uses bnpy to Python 3 and are looking forward to this release.

Till your release is official, we plan to pull code from this python3_latest branch for the duration of the transition (for testing purposes only). One of things we have had problems with bnpy in the past is that because it needs cython as a build dependency but doesn't explicitly list it (both in the Python 2 version and now the Python 3 version), a pip install always fails unless cython is already installed in the current environment. This presents a problem when we list bnpy as a dependency in our requirements.txt or environment.yml, since all packages are built in their own isolated environments (and setuptools doesn't know that it needs to cython in the one that it will use to build bnpy).

We have thus have to add a pyproject.toml to the location where we git clone your repository (see https://www.python.org/dev/peps/pep-0517/ <https://www.python.org/dev/peps/pep-0517/>) with the following content:

[build-system]
requires = ["setuptools>=40.8.0", "wheel", "cython"]
This seems to work great. You may want to add a corresponding file to your package folder as well, so we can remove the hack on our end.

**Pull request merged**
